### ISSUE TITLE
[Bug]: No `@lenra:navTo` key in type `ListenerName` 

### ISSUE THREAD

**Issue by shiipou** [lenra-io/app-lib-js#63]
### What happened?

We didn't have the `@lenra:navTo` and other system key in the  `ListenerName` type. https://github.com/lenra-io/app-lib-js/blob/main/src/lib/gen/names.ts

### Relevant log output
```
Argument of type '"@lenra:navTo"' is not assignable to parameter of type 'ListenerName'.ts(2345)
```

**Comment by taorepoara** [comment]
Might be blocking for TypeScript projects
